config/routes.rb
Rails.application.routes.draw do

  # 管理者用

  # URL /admin/sign_in ...
 namespace :admin do
   get "/homes" => "homes#top"
   resources :items, only:[:index, :create, :new, :show, :edit, :update]
   resources :genres, only:[:index, :create, :edit, :update]
   resources :customers, only:[:index, :show, :edit, :update] do
     get 'orders' => 'orders#index'
   end
   resources :orders, only: [:show, :update]
   resources :order_details, only: [:update]

 end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用

  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
# public（顧客側のルーディング）
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    # 会員
    get "customers/information" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/confirm_withdraw" => "customers#confirm_withdraw"
    patch "customers/withdraw" => "customers#withdraw"
    # 商品
    resources :items, only: [:index, :show]
    # カート内商品
    resources :cart_items, only: [:create, :index, :destroy, :update] do
      collection do
        delete :destroy_all
      end
    end

    # 注文
    post "/orders/confirm" => "orders#confirm"
    get  "/orders/complete" => "orders#complete"
    resources :orders, only:[:new, :index, :show, :create]
    # 配送先
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]

    # ジャンル検索（顧客）
    resources :genres, only:[:show]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
# order_detailsのどのidとアソシエーションするか記述
has_many :order_details
# , class_name: "OrderDetail",foreign_key: "item_id", dependent: :destroy
# order_detailsが中間テーブルであり実際結びつけるモデルを指定
has_many :orders, through: :order_details

# カート内商品：商品 = N : 1
has_many :cart_items, dependent: :destroy

# ジャンルidとのアソシエーション
belongs_to :genre, foreign_key: 'genre_id'
# ActiveStorage
has_one_attached :image

validates :name, presence: true
validates :introduction, presence: true
validates :genre, presence: true
validates :price, presence: true
# validates :image, presence: true

  def get_image(height, width)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [height, width]).processed
  end

  # 税込価格
  def add_tax_price
    tax = 1.1
    (self.price * tax).round
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_select_genres

    def index
        @item = Item.all.page(params[:page]).per(7)
    end

    def show
        @item = Item.find(params[:id])
    end

    def new
        @item = Item.new
    end

    def create
        @item = Item.new(item_params)
        if @item.save
          flash[:notice] = "Book was successfully updated."
          redirect_to admin_item_path(@item)
        else
          render 'new'
        end
    end
    def edit
        @item = Item.find(params[:id])

    end

    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
         flash[:notice] = "Book was successfully updated."
         redirect_to admin_items_path(@item)
        else
         render 'new'
        end
    end

    private
    def item_params
        params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
    end

  def set_select_genres
    @genres = Genre.all.map {|genre| [genre.name, genre.id] }.unshift(["--選択してください--", nil])
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<%= form_with model: [:admin, item] do |f| %>
      <div class="form-group row mt-5">
        <%= f.label :image, "商品画像", class: "col-4 col-form-label" %>
        <%= f.file_field :image, class: "btn" %>
      </div>
      <div class="form-group row">
        <%= f.label :name, "商品名", class: "col-4 col-form-label" %>
        <%= f.text_field :name, class: "col-7 form-control", placeholder: "商品名" %>
      </div>
      <div class="form-group row">
        <%= f.label :introduction, "商品説明", class: "col-4 col-form-label" %>
        <%= f.text_area :introduction, class: "col-7 form-control", placeholder: "ここに説明文を記述します" %>
      </div>
      <div class="form-group row">
        <%= f.label :genre, "ジャンル", class: "col-4 col-form-label" %>
        <%= f.select :genre_id, @genres,{},{class: "form-select"} %>
      </div>
      <div class="form-group row">
        <%= f.label :price, "税抜価格", class: "col-4 col-form-label" %>
        <%= f.text_field :price, class: "col-7 form-control", placeholder: "1000" %>円
      </div>
      <div class="form-group row">
        <%= f.label :is_active, "販売ステータス", class: "col-4 col-form-label" %>
        <div class="col-7 pl-0">
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>&emsp;
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
        </div>
      </div>
    <div class="form-group text-center">
      <% if request.path_info == new_admin_item_path %>
        <%= f.submit "新規登録", class: "btn btn-success px-4 py-2" %>
      <% else %>
        <%= f.submit "変更を保存", class: "btn btn-success px-4 py-2" %>
      <% end %>
    </div>
  <% end %>

app/views/admin/items/edit.html.erb
<div class="container mt-5 pb-5">
  <div class="form-group text-center">
    <h2 class="mb-3 ml-5">商品編集</h2>

    <%= render 'form', item: @item %>
  </div>
  </div>

app/views/admin/items/index.html.erb
<div class="container  mt-5 pb-5">
  <div class="col-md-12">
<h2 class="mb-3 ml-5 text-center">商品一覧</h2>

<table class="table mt-5 text-center">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @item.each do |item| %>
    <tr>
      <!--商品ID-->
      <td><%= item.id %></td>
      <!--商品名-->
      <td><%= link_to item.name, admin_item_path(item.id), class: "text-dark" %></td>
      <!--税込価格-->
      <td><%= item.price.to_s(:delimited) %></td>
      <!--ジャンル名-->
      <td><%= item.genre.name %></td>
      <!--販売ステータス-->
      <td>
        <% if item.is_active == true %>
        <p class="text-success"><strong>販売中</strong></p>
        <% else %>
        <p class="text-secondary"><strong>販売停止中</strong></p>
        <% end %>
      </td>
    </tr>
  <% end %>
 </tbody>
</table>

<div class="mb-3 ml-5 text-center">
<%= link_to "新規登録", new_admin_item_path, class: "btn btn-success" %>
</div>

<div class="row">
  <div class="mx-auto mb-5">
    <%= paginate @item %>
  </div>
</div>

</div>
</div>

      

app/views/admin/items/new.html.erb
<div class="container mt-5 pb-5">
  <div class="form-group text-center">
<h2 class="mb-3 ml-5">新規商品登録</h2>


<%= render 'form', item: @item %>
</div>
</div>

app/views/admin/items/show.html.erb
<div class="container mt-5 pb-5">
  <div class="form-group">
    <h2 class="mb-3 ml-5 text-center">商品詳細</h2>
    <div class="row mt-5 mb-5">
      <div class="col-lg-5">
       <%= image_tag @item.image,class: "rounded",size:"400x350", class: "rounded-bottom" %>
      </div>

      <div class="col-lg-7 ">
      <table class="table mx-auto">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>

          <tr>
             <td>商品説明</td>
             <td><%= @item.introduction %></td>
          </tr>

          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>

          <tr>
             <td>税込価格</br>（税抜価格）</td>
             <td><%= @item.add_tax_price.to_s(:delimited) %>（<%= @item.price.to_s(:delimited) %>）円</td>
          </tr>

           <tr>
             <td>販売ステータス</td>
             <td>
               <% if @item.is_active == true %>
                      <p class="text-success"><strong>販売中</strong></p>
               <% else %>
                      <p class="text-secondary"><strong>販売停止中</strong></p>
               <% end %>
             </td>
           </tr>
        </tbody>
       </table>
      </div>
      </div>
      <div class="text-center">
       <%= link_to "編集する", edit_admin_item_path, class: "btn btn-success mt-3 ml-5 px-4 py-2" %>
      </div>
    </div>
  </div>
</div>