config/routes.rb
Rails.application.routes.draw do

  # 管理者用

  # URL /admin/sign_in ...
 namespace :admin do
   get "/homes" => "homes#top"
   resources :items, only:[:index, :create, :new, :show, :edit, :update]
   resources :genres, only:[:index, :create, :edit, :update]
   resources :customers, only:[:index, :show, :edit, :update] do
     get 'orders' => 'orders#index'
   end
   resources :orders, only: [:show, :update]
   resources :order_details, only: [:update]

 end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用

  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
# public（顧客側のルーディング）
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    # 会員
    get "customers/information" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/confirm_withdraw" => "customers#confirm_withdraw"
    patch "customers/withdraw" => "customers#withdraw"
    # 商品
    resources :items, only: [:index, :show]
    # カート内商品
    resources :cart_items, only: [:create, :index, :destroy, :update] do
      collection do
        delete :destroy_all
      end
    end

    # 注文
    post "/orders/confirm" => "orders#confirm"
    get  "/orders/complete" => "orders#complete"
    resources :orders, only:[:new, :index, :show, :create]
    # 配送先
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]

    # ジャンル検索（顧客）
    resources :genres, only:[:show]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # カート内商品：会員 = N : 1
  has_many :cart_items, dependent: :destroy

  has_many :addresses, dependent: :destroy

  has_many :orders, dependent: :destroy

validates :last_name, presence: true
validates :first_name, presence: true
validates :last_name_kana, presence: true
validates :first_name_kana, presence: true
validates :postal_code, presence: true
validates :address, presence: true
validates :telephone_number, presence: true
validates :email, presence: true

# ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないよう制約
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
   @customers = Customer.find(params[:id])
  end

  def edit
    @customers = Customer.find(params[:id])
  end

  def update
   @customers = Customer.find(params[:id])
   if @customers.update(customer_params)
     flash[:notice] = "更新情報を更新しました"
     redirect_to admin_customers_path
   else
     render :edit
    end
  end

  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
    end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5"><%= @customers.last_name %> <%= @customers.first_name %>さんの会員情報編集</h4>
      <%= form_with model: @customers, url: admin_customer_path, method: :patch do |f| %>
      <table class="table table-borderless">

        <tr>
          <td>会員ID</td>
          <td><%= @customers.id %></td>
        </tr>

        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name %>　<%= f.text_field :first_name %></td>
        </tr>

        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :last_name_kana %>　<%= f.text_field :first_name_kana %></td>
        </tr>

        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :postal_code %></td>
          <td></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= f.text_field :address %></td>
          <td></td>
        </tr>

        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :telephone_number %></td>
          <td></td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email %></td>
          <td></td>
        </tr>

        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効", { value: :false }  %>

            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会", { value: :true } %>
          </td>
        </tr>

        <tr>
          <td></td>
          <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
        </tr>

      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
    <h2 class="text-center mt-5 mb-5">会員一覧</h2>
     <div class="d-flex align-items-center">


      <table class="table text-center">
        <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.last_name %> <%= customer.first_name %>
              <% end %>
            </td>
            <td>
              <%= customer.email %>
            </td>
           <td class= "<%= customer.is_deleted ? 'text-gray' : 'text-green' %>"><%= customer.is_deleted ? '退会済み' : '有効' %>
           </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
 </div>
 </div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5"><%= @customers.last_name %>　<%= @customers.first_name %>さんの会員詳細</h4>
      <div class="d-flex align-items-center">
        <table class="table table-borderless">
          <tr>
            <th>会員ID</td>
            <td><%= @customers.id %></td>
          </tr>
          <tr>
            <th>氏名</td>
            <td><%= @customers.last_name %>　<%= @customers.first_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= @customers.last_name_kana %>　<%= @customers.first_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= @customers.postal_code %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= @customers.address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= @customers.telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @customers.email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <% if @customers.is_deleted %>
            <th class='text-success  font-weight-bold'><%= "退会" %></th>
            <% else %>
            <th class='text-muted font-weight-block'><%= "有効" %></th>
            <% end %>
          </tr>
          <tr class=>
            <td></td>
            <td class=><%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success mr-2" %>
            <%= link_to "注文履歴一覧を見る", admin_customer_orders_path(@customers), class:"btn btn-primary ml-2" %></td>
        </tr>
        </table>



      <!--</div>-->
    </div>
  </div>
</div>