config/routes.rb
Rails.application.routes.draw do

  # 管理者用

  # URL /admin/sign_in ...
 namespace :admin do
   get "/homes" => "homes#top"
   resources :items, only:[:index, :create, :new, :show, :edit, :update]
   resources :genres, only:[:index, :create, :edit, :update]
   resources :customers, only:[:index, :show, :edit, :update] do
     get 'orders' => 'orders#index'
   end
   resources :orders, only: [:show, :update]
   resources :order_details, only: [:update]

 end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用

  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
# public（顧客側のルーディング）
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    # 会員
    get "customers/information" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/confirm_withdraw" => "customers#confirm_withdraw"
    patch "customers/withdraw" => "customers#withdraw"
    # 商品
    resources :items, only: [:index, :show]
    # カート内商品
    resources :cart_items, only: [:create, :index, :destroy, :update] do
      collection do
        delete :destroy_all
      end
    end

    # 注文
    post "/orders/confirm" => "orders#confirm"
    get  "/orders/complete" => "orders#complete"
    resources :orders, only:[:new, :index, :show, :create]
    # 配送先
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]

    # ジャンル検索（顧客）
    resources :genres, only:[:show]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  # created_at の値を 降順 で並び替えてくれる
  scope :latest, -> { order(created_at: :desc) }
  
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # 会員・商品：カート内商品= 1 : N
  belongs_to :customer
  belongs_to :item

  def get_image(height, width)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [height, width]).processed
  end
  # 税込価格
  def add_tax_price
    tax = 1.1
    (item.price * tax).round
  end

  # 小計
  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # カート内商品：会員 = N : 1
  has_many :cart_items, dependent: :destroy

  has_many :addresses, dependent: :destroy

  has_many :orders, dependent: :destroy

validates :last_name, presence: true
validates :first_name, presence: true
validates :last_name_kana, presence: true
validates :first_name_kana, presence: true
validates :postal_code, presence: true
validates :address, presence: true
validates :telephone_number, presence: true
validates :email, presence: true

# ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないよう制約
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  # itemとジャンルidでのアソシエーション
  has_many :items, foreign_key: "genre_id"

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
# order_detailsのどのidとアソシエーションするか記述
has_many :order_details
# , class_name: "OrderDetail",foreign_key: "item_id", dependent: :destroy
# order_detailsが中間テーブルであり実際結びつけるモデルを指定
has_many :orders, through: :order_details

# カート内商品：商品 = N : 1
has_many :cart_items, dependent: :destroy

# ジャンルidとのアソシエーション
belongs_to :genre, foreign_key: 'genre_id'
# ActiveStorage
has_one_attached :image

validates :name, presence: true
validates :introduction, presence: true
validates :genre, presence: true
validates :price, presence: true
# validates :image, presence: true

  def get_image(height, width)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [height, width]).processed
  end

  # 税込価格
  def add_tax_price
    tax = 1.1
    (self.price * tax).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  # order_detailsのどのidとアソシエーションするか記述
 has_many :order_details
 # , class_name: "OrderDetail",foreign_key: "order_id", dependent: :destroy
# order_detailsが中間テーブルであり実際結びつけるモデルを指定
 has_many :items, through: :order_details
# 会員　:　注文　＝　１　：　N
 belongs_to :customer

# 支払い方法 {0:クレジットカード、1:銀行振込}
enum payment_method: { credit_card: 0, transfer: 1}

# 注文ステータス {0:入金待ち、1:入金確認、2:制作中、3:発送準備中、4:発送済み}
enum status: {waiting_payment: 0, confirm_payment: 1, producting: 2, waiting_delivery: 3, start_delivery: 4}

# お届け先　｛自分の住所　登録済み住所　新規住所｝
enum select_address: { own_address: 0, registered_address: 1, new_address: 2}

def total
    order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal }
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

belongs_to :item
belongs_to :order

# 制作ステータス {0:着手不可、1:制作待ち、2:制作中、3:製作完了}
enum making_status: {impossible: 0, waiting: 1, producting: 2, completion: 3}

## 小計を求めるメソッド
  def subtotal
    item.add_tax_price * amount
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.all.order(created_at: :desc).page(params[:page]).per(5)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_select_genres

    def index
        @item = Item.all.page(params[:page]).per(7)
    end

    def show
        @item = Item.find(params[:id])
    end

    def new
        @item = Item.new
    end

    def create
        @item = Item.new(item_params)
        if @item.save
          flash[:notice] = "Book was successfully updated."
          redirect_to admin_item_path(@item)
        else
          render 'new'
        end
    end
    def edit
        @item = Item.find(params[:id])

    end

    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
         flash[:notice] = "Book was successfully updated."
         redirect_to admin_items_path(@item)
        else
         render 'new'
        end
    end

    private
    def item_params
        params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
    end

  def set_select_genres
    @genres = Genre.all.map {|genre| [genre.name, genre.id] }.unshift(["--選択してください--", nil])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # 顧客ログイン後の遷移先（トップ）
  def after_sign_in_path_for(resource)
    case resource
      when Customer
        root_path
    end
  end

  # ログアウト後の遷移先（トップ）
  def after_sign_out_path_for(resource)
    root_path
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container mx-auto">
      <a class="navbar-brand m-0 " href="/"><%= image_tag('na.png') %></a>
        <ul class="navbar-nav ml-auto">

       <div class="login-name mx-auto text-light">
        <% if customer_signed_in? %>
        <p>ようこそ, <%= current_customer.last_name %> さん！</p>
　　　　<% elsif admin_signed_in? %>
　　　　<p>管理者　ログイン中</p>
　　　　<% end %>
　　　</div>

　　　　<ul class="nav navbar-nav navbar-right">
　　　　  <% if customer_signed_in? %>
　　　　  <!--ユーザーがログインしているとき-->
          <li>
            <%= link_to customers_information_path,class: 'nav-link text-light' do %>
              マイページ
            <% end %>
          </li>

          <li>
            <%=  link_to items_path,class: 'nav-link text-light' do %>
               商品一覧
            <% end %>
          </li>

          <li>
            <%=  link_to cart_items_path ,class: 'nav-link text-light' do %>
               カート
            <% end %>
          </li>

          <li>
            <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light' do %>
               ログアウト
            <% end %>
          </li>

          <form class="search">
            <%= form_with model: @genre do |f| %>
                <%= f.text_field :genre, placeholder: "キーワード検索" %>
                  <i class="fas fa-search" style="color: #f7f9fc;"></i>
                <% f.submit %>
              <% end %>
            </div>


          <% elsif admin_signed_in? %>
          <!--管理車がログインしているとき-->
          <li>
            <%= link_to admin_items_path, class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_customers_path, class: 'nav-link text-light' do %>
              会員一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_homes_path, class: 'nav-link text-light' do %>
              注文履歴一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_genres_path, class: 'nav-link text-light' do %>
              ジャンル一覧
            <% end %>
          </li>
          <li>
            <%=  link_to destroy_admin_session_path, class: 'nav-link text-light', method: :delete do %>
              ログアウト
            <% end %>
          </li>

          <div class="search mt-2 ml-1">
            <%= form_with  do |f| %>
                <%= f.text_field :genre, placeholder: "キーワード検索" %>
                  <i class="fas fa-search" style="color: #f7f9fc;"></i>
                <% f.submit %>
              <% end %>
            </div>

          <% else %>
　　　　　<!--誰もログインしていないとき-->
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
               About
            <% end %>
          </li>

          <li>
            <%= link_to items_path,class: 'nav-link text-light' do %>
               商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>
               新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path ,class: 'nav-link text-light' do %>
               ログイン
            <% end %>
          </li>

        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0c41007c71.js" crossorigin="anonymous"></script>
    <%#= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Zen+Kurenaido&display=swap" rel="stylesheet">


  </head>

  <body>

  <%= render 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>